CREATE TABLE Course(
    COURSE_ID INTEGER PRIMARY KEY NOT NULL,
    COURSE_NAME NVARCHAR
);

CREATE TABLE Task(
    TASK_ID INTEGER PRIMARY KEY NOT NULL,
    COURSE_ID INTEGER NOT NULL,
    TASK_NUMBER INTEGER,
    NAME NVARCHAR,
    FOLDER_LINK NVARCHAR,
    FOREIGN KEY(COURSE_ID) REFERENCES Course(COURSE_ID)
);

CREATE TABLE Student(
    STUDENT_ID INTEGER PRIMARY KEY NOT NULL,
    COURSE_ID INTEGER NOT NULL,
    STUDENT_NUMBER NVARCHAR(14) NOT NULL,
    FULL_NAME NVARCHAR,
    EMAIL NVARCHAR,
    PASSWORD_HASH NVARCHAR,
    FOLDER_LINK NVARCHAR,
    FOREIGN KEY(COURSE_ID) REFERENCES Course(COURSE_ID)
);

CREATE TABLE Student_Task(
    STUDENT_ID INTEGER NOT NULL,
    TASK_ID INTEGER NOT NULL,
    REVIEW_SUBMITTED BOOLEAN DEFAULT 0,
    GRADE INTEGER DEFAULT NULL
);

CREATE TABLE Task_Review(
    REVIEW_ID INTEGER NOT NULL PRIMARY KEY,
    STUDENT_ID INTEGER NOT NULL,
    TASK_ID INTEGER NOT NULL,
    FOREIGN KEY(STUDENT_ID) REFERENCES Student(STUDENT_ID),
    FOREIGN KEY(TASK_ID) REFERENCES Task(TASK_ID)
    UNIQUE(STUDENT_ID, TASK_ID) 
)